# MoonLakeEconomy 月色之湖经济插件
# 作者：Month_Light

# 插件版本号
version: 1.3

# 数据库配置
MySQL:
  
  # 数据库的名称
  mySQLDatabase: moonlake_economy

  # 数据库的地址
  mySQLHost: 127.0.0.1

  # 数据库的端口
  mySQLPort: 3306

  # 数据库的用户名
  mySQLUsername: root

  # 数据库的密码
  mySQLPassword: moonlake

  # 数据库的表名
  mySQLTableName: economy

# 基础配置
Setting:

  # 是否开启账户经济变动日志信息
  Logger: true

  # 玩家默认进服的金币
  DefaultMoney: 0.0

  # 玩家默认进服的点券
  DefaultPoint: 0